# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Desktop\CTFMiscTools\TomatoTools\GUI\Cipher.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cipher(object):
    def setupUi(self, Cipher):
        Cipher.setObjectName("Cipher")
        Cipher.resize(578, 326)
        Cipher.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Cipher)
        self.centralwidget.setStyleSheet("QPushButton{\n"
"        border:2px solid gray;\n"
"        border-radius:19px;\n"
"}\n"
"QWidget{\n"
"        background:white;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 30, 531, 161))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 220, 111, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/GUI/images/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 220, 61, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 220, 141, 41))
        self.lineEdit_2.setStyleSheet("*{\n"
"        border-radius:19px;\n"
"}")
        self.lineEdit_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.HongKong))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_2.setObjectName("lineEdit_2")
        Cipher.setCentralWidget(self.centralwidget)

        self.retranslateUi(Cipher)
        QtCore.QMetaObject.connectSlotsByName(Cipher)

    def retranslateUi(self, Cipher):
        _translate = QtCore.QCoreApplication.translate
        Cipher.setWindowTitle(_translate("Cipher", "MainWindow"))
        self.plainTextEdit.setPlaceholderText(_translate("Cipher", "在这里输入密文"))
        self.pushButton.setText(_translate("Cipher", "自动分析"))
        self.lineEdit_2.setPlaceholderText(_translate("Cipher", "密钥(可忽略不写)"))
import res_rc
