# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Desktop\CTFMiscTools\CTF密码学工具\GUI\GetFlag.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GetFlag(object):
    def setupUi(self, GetFlag):
        GetFlag.setObjectName("GetFlag")
        GetFlag.resize(550, 336)
        self.centralwidget = QtWidgets.QWidget(GetFlag)
        self.centralwidget.setStyleSheet("QPushButton{\n"
"        border:2px solid gray;\n"
"        border-radius:19px;\n"
"}\n"
"\n"
"QWidget{\n"
"        background:white;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 30, 461, 151))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 210, 151, 41))
        self.lineEdit.setStyleSheet("*{\n"
"        border:1px solid gray;\n"
"        border-radius:5px;\n"
"}")
        self.lineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.HongKong))
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 210, 141, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/GUI/images/5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 210, 61, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 260, 141, 41))
        self.lineEdit_2.setStyleSheet("*{\n"
"        border-radius:19px;\n"
"}")
        self.lineEdit_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.HongKong))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(330, 260, 131, 41))
        self.radioButton.setObjectName("radioButton")
        GetFlag.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(GetFlag)
        self.statusBar.setObjectName("statusBar")
        GetFlag.setStatusBar(self.statusBar)

        self.retranslateUi(GetFlag)
        QtCore.QMetaObject.connectSlotsByName(GetFlag)

    def retranslateUi(self, GetFlag):
        _translate = QtCore.QCoreApplication.translate
        GetFlag.setWindowTitle(_translate("GetFlag", "MainWindow"))
        self.plainTextEdit.setPlaceholderText(_translate("GetFlag", "在这里输入密文"))
        self.lineEdit.setPlaceholderText(_translate("GetFlag", "flag关键词"))
        self.pushButton.setText(_translate("GetFlag", "自动提flag"))
        self.lineEdit_2.setPlaceholderText(_translate("GetFlag", "密钥(可忽略不写)"))
        self.radioButton.setText(_translate("GetFlag", "导出分析日志"))
import res_rc
