# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Desktop\CTFMiscTools\utf-8' 'CTF密码学工具\CTF密码学工具\GUI\Plug.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Plug(object):
    def setupUi(self, Plug):
        Plug.setObjectName("Plug")
        Plug.resize(516, 313)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Plug.sizePolicy().hasHeightForWidth())
        Plug.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Plug)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("QPushButton{\n"
"        border:2px solid gray;\n"
"        border-radius:20px;\n"
"}\n"
"QWidget{\n"
"        background:white;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setGeometry(QtCore.QRect(270, 120, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setGeometry(QtCore.QRect(190, 120, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setStyleSheet("")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(100, 0, 291, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 160, 171, 101))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(60, 160, 171, 101))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        Plug.setCentralWidget(self.centralwidget)

        self.retranslateUi(Plug)
        QtCore.QMetaObject.connectSlotsByName(Plug)

    def retranslateUi(self, Plug):
        _translate = QtCore.QCoreApplication.translate
        Plug.setWindowTitle(_translate("Plug", "MainWindow"))
        self.radioButton_2.setText(_translate("Plug", "删除"))
        self.radioButton.setText(_translate("Plug", "添加"))
        self.label.setText(_translate("Plug", "<html><head/><body><p align=\"center\"><img src=\":/icons/GUI/images/10.png\"/><img src=\":/icons/GUI/images/9.png\"/><img src=\":/icons/GUI/images/15.png\"/><img src=\":/icons/GUI/images/14.png\"/></p><p align=\"center\"><span style=\" font-size:22pt; vertical-align:sub;\">插件管理</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Plug", "解密插件Decode"))
        self.pushButton.setText(_translate("Plug", "加密插件Encode"))
import res_rc
