# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Desktop\CTFMiscTools\utf-8' 'CTF密码学工具\CTF密码学工具\GUI\QWFormDoc.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QWFormDoc(object):
    def setupUi(self, QWFormDoc):
        QWFormDoc.setObjectName("QWFormDoc")
        QWFormDoc.resize(661, 379)
        font = QtGui.QFont()
        font.setPointSize(10)
        QWFormDoc.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(QWFormDoc)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(QWFormDoc)
        self.plainTextEdit.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(QWFormDoc)
        QtCore.QMetaObject.connectSlotsByName(QWFormDoc)

    def retranslateUi(self, QWFormDoc):
        _translate = QtCore.QCoreApplication.translate
        QWFormDoc.setWindowTitle(_translate("QWFormDoc", "new document"))
